export type UserRole = 'admin' | 'manager' | 'user';

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  department: string;
  xp: number;
  points: number;
  badges: string[]; // Badge IDs
  avatar: string;
}

export interface Department {
  id: string;
  name: string;
  code: string;
  head: string;
  parentDept: string;
  employeeCount: number;
  status: 'Active' | 'Archived';
}

export interface Category {
  id: string;
  name: string;
  type: 'CSR Activity' | 'Challenge Category';
  status: 'Active' | 'Archived';
}

export interface EmissionFactor {
  id: string;
  activityType: string;
  unit: string;
  co2PerUnit: number;
  source: string;
}

export interface ProductESGProfile {
  id: string;
  productName: string;
  category: string;
  carbonFootprint: number; // kg CO2e
  recyclability: number; // %
  esgRating: 'AAA' | 'AA' | 'A' | 'BBB' | 'BB' | 'B' | 'CCC';
}

export interface EnvironmentalGoal {
  id: string;
  name: string;
  department: string;
  targetCO2: number;
  currentCO2: number;
  deadline: string;
  status: 'Active' | 'On Track' | 'Completed' | 'At Risk';
}

export interface ESGPolicy {
  id: string;
  title: string;
  category: string;
  description: string;
  effectiveDate: string;
  status: 'Active' | 'Draft' | 'Archived';
}

export interface Badge {
  id: string;
  name: string;
  description: string;
  unlockRule: string; // e.g. "XP >= 1000", "Completed Challenges >= 5"
  icon: string; // Lucide icon key
}

export interface Reward {
  id: string;
  name: string;
  description: string;
  pointsRequired: number;
  stock: number;
  status: 'Active' | 'Out of Stock' | 'Archived';
}

export interface CarbonTransaction {
  id: string;
  department: string;
  sourceType: 'Purchase' | 'Manufacturing' | 'Expense' | 'Fleet';
  emissionFactorId: string;
  quantity: number;
  co2Calculated: number;
  date: string;
  autoGenerated: boolean;
}

export interface CSRActivity {
  id: string;
  title: string;
  category: string;
  description: string;
  joinedCount: number;
  evidenceRequired: boolean;
  status: 'Active' | 'Draft' | 'Completed' | 'Archived';
  deadline: string;
}

export interface EmployeeParticipation {
  id: string;
  employeeName: string;
  employeeEmail: string;
  activityId: string;
  proofFile?: string;
  approvalStatus: 'Pending' | 'Approved' | 'Rejected';
  pointsEarned: number;
  completionDate?: string;
}

export interface Challenge {
  id: string;
  title: string;
  category: string;
  description: string;
  xp: number;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  evidenceRequired: boolean;
  deadline: string;
  status: 'Draft' | 'Active' | 'Under Review' | 'Completed' | 'Archived';
}

export interface ChallengeParticipation {
  id: string;
  challengeId: string;
  employeeName: string;
  employeeEmail: string;
  progress: number; // 0 to 100
  proofFile?: string;
  approvalStatus: 'Pending' | 'Approved' | 'Rejected';
  xpAwarded: number;
}

export interface PolicyAcknowledgement {
  id: string;
  policyId: string;
  employeeName: string;
  employeeEmail: string;
  acknowledgedDate?: string;
  status: 'Pending' | 'Acknowledged';
}

export interface Audit {
  id: string;
  title: string;
  department: string;
  auditor: string;
  date: string;
  findings: string;
  status: 'Completed' | 'Under Review' | 'Pending';
}

export interface ComplianceIssue {
  id: string;
  auditId: string;
  severity: 'High' | 'Medium' | 'Low';
  description: string;
  owner: string;
  dueDate: string;
  status: 'Open' | 'Resolved';
}

export interface DepartmentScore {
  id: string;
  department: string;
  environmentalScore: number;
  socialScore: number;
  governanceScore: number;
  totalScore: number;
}

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  type: 'compliance' | 'participation' | 'policy' | 'badge' | 'general';
  read: boolean;
  date: string;
}

export interface ESGScores {
  environmental: number;
  social: number;
  governance: number;
  overall: number;
}
