import React, { useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { useNavigate } from 'react-router-dom';
import { RootState, addCarbonTransaction, addToast } from '../store';
import { KPITile } from '../components/KPITile';
import { Modal } from '../components/Modal';
import { LineChart, Line, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { Plus, Play, FileText, ChevronRight, AlertTriangle, ArrowUpRight, TrendingUp } from 'lucide-react';

export const DashboardPage: React.FC = () => {
  const dispatch = useDispatch();
  const navigate = useNavigate();
  const currentUser = useSelector((state: RootState) => state.auth.currentUser);
  const weights = useSelector((state: RootState) => state.settings.weights);
  const departments = useSelector((state: RootState) => state.departments);
  const factors = useSelector((state: RootState) => state.emissionFactors);
  const carbonTransactions = useSelector((state: RootState) => state.carbonTransactions);
  const issues = useSelector((state: RootState) => state.complianceIssues);
  const goals = useSelector((state: RootState) => state.goals);

  const [isLogOpen, setIsLogOpen] = useState(false);
  const [logDept, setLogDept] = useState(currentUser?.department || 'Manufacturing');
  const [logSource, setLogSource] = useState<'Purchase' | 'Manufacturing' | 'Expense' | 'Fleet'>('Manufacturing');
  const [logFactor, setLogFactor] = useState('ef1');
  const [logQty, setLogQty] = useState('');

  // 1. CALCULATE SCORE DYNAMICS
  // Sub-scores can be aggregated or defined by defaults
  const environmentalScore = 82;
  const socialScore = 74;
  const governanceScore = 88;

  const totalWeight = weights.environmental + weights.social + weights.governance;
  const overallScore = Math.round(
    (environmentalScore * weights.environmental +
      socialScore * weights.social +
      governanceScore * weights.governance) /
      (totalWeight || 100)
  );

  // Scoped view info for Manager
  const isManager = currentUser?.role === 'manager';
  const scopeText = isManager ? `Scoped: ${currentUser?.department} Dept` : 'Organization-Wide Overview';

  // 2. CHART DATA FORMULATION
  const emissionsTrendData = [
    { month: 'Aug 25', co2: 52000 },
    { month: 'Sep 25', co2: 48000 },
    { month: 'Oct 25', co2: 55000 },
    { month: 'Nov 25', co2: 53000 },
    { month: 'Dec 25', co2: 61000 },
    { month: 'Jan 26', co2: 49000 },
    { month: 'Feb 26', co2: 45000 },
    { month: 'Mar 26', co2: 47000 },
    { month: 'Apr 26', co2: 42000 },
    { month: 'May 26', co2: 38000 },
    { month: 'Jun 26', co2: 41000 },
    { month: 'Jul 26', co2: Math.round(carbonTransactions.reduce((acc, curr) => acc + curr.co2Calculated, 0)) }
  ];

  const departmentRankingData = [
    { name: 'Mfg', score: 85, color: '#22c55e' },
    { name: 'Log', score: 72, color: '#3b82f6' },
    { name: 'Corp', score: 91, color: '#a855f7' },
    { name: 'Sales', score: 79, color: '#f97316' },
    { name: 'R&D', score: 88, color: '#94a3b8' }
  ];

  // Overdue issue count
  const today = '2026-07-12';
  const overdueIssues = issues.filter(i => i.status === 'Open' && i.dueDate < today);

  const handleLogCarbon = (e: React.FormEvent) => {
    e.preventDefault();
    const qty = parseFloat(logQty);
    if (isNaN(qty) || qty <= 0) {
      dispatch(addToast({ message: 'Please enter a valid positive quantity!', type: 'error' }));
      return;
    }

    dispatch(addCarbonTransaction({
      department: logDept,
      sourceType: logSource,
      emissionFactorId: logFactor,
      quantity: qty,
      date: new Date().toISOString().split('T')[0],
      autoGenerated: false
    }));

    dispatch(addToast({ message: 'Carbon Transaction logged successfully!', type: 'success' }));
    setIsLogOpen(false);
    setLogQty('');
  };

  return (
    <div className="p-6 space-y-6">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#262b36] pb-5">
        <div>
          <h1 className="text-xl font-bold text-white tracking-tight">EXECUTIVE OVERVIEW</h1>
          <p className="text-xs text-gray-400 mt-1">{scopeText} • System Time: 2026-07-12</p>
        </div>
        <div className="flex items-center gap-2">
          {overdueIssues.length > 0 && (
            <div className="flex items-center gap-1.5 px-3 py-1 bg-red-500/10 border border-red-500/30 text-red-400 text-xs font-bold rounded-lg pulsing-alert">
              <AlertTriangle className="w-4 h-4" />
              {overdueIssues.length} Compliance Issues Overdue!
            </div>
          )}
        </div>
      </div>

      {/* 4 Score KPIs */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <KPITile
          title="Environmental Score"
          value={`${environmentalScore} / 100`}
          subtext="Greenhouse gases & materials"
          trend="up"
          trendValue="+4%"
          accentColor="green"
          onClick={() => navigate('/environmental/goals')}
        />
        <KPITile
          title="Social Score"
          value={`${socialScore} / 100`}
          subtext="Employee engagement & diversity"
          trend="up"
          trendValue="+1%"
          accentColor="blue"
          onClick={() => navigate('/social/csr-activities')}
        />
        <KPITile
          title="Governance Score"
          value={`${governanceScore} / 100`}
          subtext="Audit readiness & compliance"
          trend="neutral"
          trendValue="0%"
          accentColor="purple"
          onClick={() => navigate('/governance/audits')}
        />
        <KPITile
          title="Overall ESG Score"
          value={`${overallScore} / 100`}
          subtext={`Weighted: ${weights.environmental}% E / ${weights.social}% S / ${weights.governance}% G`}
          trend="up"
          trendValue="+3%"
          accentColor="slate"
        />
      </div>

      {/* Double Charts Column */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Line Chart: Carbon Emissions */}
        <div className="bg-[#161a22] border border-[#262b36] rounded-xl p-5 lg:col-span-2">
          <div className="flex justify-between items-center mb-4">
            <div>
              <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest">Emissions Trend (12 mo)</h3>
              <p className="text-[10px] text-gray-500">Total metric tonnes of CO2 equivalent</p>
            </div>
            <span className="text-[10px] bg-green-500/10 text-green-400 border border-green-500/20 px-2 py-0.5 rounded-full font-semibold">
              Carbon Accounting Active
            </span>
          </div>
          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={emissionsTrendData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1f242e" />
                <XAxis dataKey="month" stroke="#4b5563" fontSize={10} tickLine={false} />
                <YAxis stroke="#4b5563" fontSize={10} tickLine={false} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#161a22', border: '1px solid #262b36' }}
                  labelStyle={{ color: '#94a3b8', fontSize: 11 }}
                  itemStyle={{ color: '#22c55e', fontSize: 11 }}
                />
                <Line
                  type="monotone"
                  dataKey="co2"
                  name="kg CO2"
                  stroke="#22c55e"
                  strokeWidth={3}
                  activeDot={{ r: 6 }}
                  dot={{ r: 3 }}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Bar Chart: Dept Rankings */}
        <div className="bg-[#161a22] border border-[#262b36] rounded-xl p-5">
          <div className="flex justify-between items-center mb-4">
            <div>
              <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest">Department ESG Ranking</h3>
              <p className="text-[10px] text-gray-500">Combined average sustainability indices</p>
            </div>
            <TrendingUp className="w-4 h-4 text-slate-500" />
          </div>
          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={departmentRankingData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1f242e" />
                <XAxis dataKey="name" stroke="#4b5563" fontSize={10} tickLine={false} />
                <YAxis stroke="#4b5563" fontSize={10} tickLine={false} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#161a22', border: '1px solid #262b36' }}
                  labelStyle={{ color: '#94a3b8', fontSize: 11 }}
                  itemStyle={{ color: '#3b82f6', fontSize: 11 }}
                />
                <Bar dataKey="score" fill="#3b82f6" radius={[4, 4, 0, 0]}>
                  {departmentRankingData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Bottom section: Recent Activity + Quick Actions */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Recent Activity Ledgers */}
        <div className="bg-[#161a22] border border-[#262b36] rounded-xl p-5 lg:col-span-2">
          <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">Recent Activity Feed</h3>
          <div className="space-y-3.5">
            <div className="flex items-start gap-3 p-3 bg-[#0d0f14]/50 border border-[#262b36] rounded-xl hover:bg-[#0d0f14] transition-colors">
              <span className="w-2 h-2 rounded-full bg-green-500 mt-1.5 flex-shrink-0"></span>
              <div className="flex-1 min-w-0">
                <p className="text-xs text-white">
                  <strong>Aditi Rao</strong> completed challenge <span className="text-orange-400 font-semibold">'Sustainability Sprint'</span>
                </p>
                <p className="text-[10px] text-gray-500 mt-0.5">Approved in Manufacturing • +200 XP earned</p>
              </div>
              <span className="text-[10px] text-gray-600 font-mono">1 hr ago</span>
            </div>

            <div className="flex items-start gap-3 p-3 bg-[#0d0f14]/50 border border-[#262b36] rounded-xl hover:bg-[#0d0f14] transition-colors">
              <span className="w-2 h-2 rounded-full bg-red-500 mt-1.5 flex-shrink-0 pulsing-alert"></span>
              <div className="flex-1 min-w-0">
                <p className="text-xs text-white">
                  New compliance anomaly raised: <span className="text-red-400 font-semibold">'Missing MSDS sheets'</span>
                </p>
                <p className="text-[10px] text-gray-500 mt-0.5">Assigned to Marcus Vance • High Severity • Overdue</p>
              </div>
              <span className="text-[10px] text-gray-600 font-mono">10 hr ago</span>
            </div>

            <div className="flex items-start gap-3 p-3 bg-[#0d0f14]/50 border border-[#262b36] rounded-xl hover:bg-[#0d0f14] transition-colors">
              <span className="w-2 h-2 rounded-full bg-purple-500 mt-1.5 flex-shrink-0"></span>
              <div className="flex-1 min-w-0">
                <p className="text-xs text-white">
                  <strong>42 new Carbon Transactions</strong> auto-calculated from Manufacturing & Logistics
                </p>
                <p className="text-[10px] text-gray-500 mt-0.5">Emission calculator toggle was triggered ON</p>
              </div>
              <span className="text-[10px] text-gray-600 font-mono">Yesterday</span>
            </div>

            <div className="flex items-start gap-3 p-3 bg-[#0d0f14]/50 border border-[#262b36] rounded-xl hover:bg-[#0d0f14] transition-colors">
              <span className="w-2 h-2 rounded-full bg-blue-500 mt-1.5 flex-shrink-0"></span>
              <div className="flex-1 min-w-0">
                <p className="text-xs text-white">
                  Research & Development acknowledged the <span className="text-purple-400 font-semibold">'Supplier Code of Conduct'</span> policy
                </p>
                <p className="text-[10px] text-gray-500 mt-0.5">100% compliance registered for Tier-1 laboratories</p>
              </div>
              <span className="text-[10px] text-gray-600 font-mono">2 days ago</span>
            </div>
          </div>
        </div>

        {/* Quick Actions Panel */}
        <div className="bg-[#161a22] border border-[#262b36] rounded-xl p-5 flex flex-col justify-between">
          <div>
            <h3 className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-4">Quick Actions Dock</h3>
            <p className="text-xs text-gray-400 leading-relaxed mb-6">
              Access transactional logs, join employee challenges, or render custom audit sheets instantly.
            </p>
          </div>
          <div className="space-y-3">
            <button
              onClick={() => setIsLogOpen(true)}
              className="w-full bg-green-500 hover:bg-green-600 text-black font-bold py-2.5 rounded-xl text-xs uppercase tracking-wider transition-all flex items-center justify-center gap-2 cursor-pointer"
            >
              <Plus className="w-4 h-4" /> Log Carbon Data
            </button>
            <button
              onClick={() => navigate('/gamification/challenges')}
              className="w-full bg-orange-500 hover:bg-orange-600 text-black font-bold py-2.5 rounded-xl text-xs uppercase tracking-wider transition-all flex items-center justify-center gap-2 cursor-pointer"
            >
              <Play className="w-4 h-4" /> Start Challenge
            </button>
            <button
              onClick={() => navigate('/reports/environmental')}
              className="w-full bg-[#0d0f14] hover:bg-[#161a22] text-white border border-[#262b36] hover:border-slate-500 font-bold py-2.5 rounded-xl text-xs uppercase tracking-wider transition-all flex items-center justify-center gap-2 cursor-pointer"
            >
              <FileText className="w-4 h-4" /> View Reports
            </button>
          </div>
        </div>
      </div>

      {/* Manual Carbon Logging Modal */}
      <Modal isOpen={isLogOpen} onClose={() => setIsLogOpen(false)} title="Log Carbon Transaction">
        <form onSubmit={handleLogCarbon} className="space-y-4">
          <div>
            <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">
              Target Department
            </label>
            <select
              value={logDept}
              onChange={(e) => setLogDept(e.target.value)}
              className="w-full bg-[#0d0f14] border border-[#262b36] rounded-xl p-2.5 text-xs text-white focus:outline-none focus:border-slate-500"
            >
              {departments.map(d => (
                <option key={d.id} value={d.name}>{d.name}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">
              Source Type
            </label>
            <select
              value={logSource}
              onChange={(e) => setLogSource(e.target.value as any)}
              className="w-full bg-[#0d0f14] border border-[#262b36] rounded-xl p-2.5 text-xs text-white focus:outline-none focus:border-slate-500"
            >
              <option value="Manufacturing">Manufacturing Operation</option>
              <option value="Purchase">Purchase & Procurement</option>
              <option value="Fleet">Logistics Fleet</option>
              <option value="Expense">Expense & Travel</option>
            </select>
          </div>

          <div>
            <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">
              Emission Factor Type
            </label>
            <select
              value={logFactor}
              onChange={(e) => setLogFactor(e.target.value)}
              className="w-full bg-[#0d0f14] border border-[#262b36] rounded-xl p-2.5 text-xs text-white focus:outline-none focus:border-slate-500"
            >
              {factors.map(f => (
                <option key={f.id} value={f.id}>
                  {f.activityType} ({f.unit})
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">
              Resource Quantity
            </label>
            <input
              type="number"
              required
              value={logQty}
              onChange={(e) => setLogQty(e.target.value)}
              className="w-full bg-[#0d0f14] border border-[#262b36] rounded-xl p-2.5 text-xs text-white focus:outline-none focus:border-slate-500"
              placeholder="e.g. 5000"
              min="0.01"
              step="any"
            />
          </div>

          <div className="pt-4 flex justify-end gap-3 border-t border-[#262b36]">
            <button
              type="button"
              onClick={() => setIsLogOpen(false)}
              className="px-4 py-2 bg-[#0d0f14] border border-[#262b36] hover:border-slate-500 text-xs font-bold rounded-xl text-gray-400 hover:text-white uppercase tracking-wider transition-all"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-green-500 hover:bg-green-600 text-black text-xs font-bold rounded-xl uppercase tracking-wider transition-all cursor-pointer"
            >
              Record Data
            </button>
          </div>
        </form>
      </Modal>
    </div>
  );
};
